version 1
ildarzinatulin/smart-home-2020 pull request #1
Opened 2020-02-29 15:55 UTC by ildarzinatulin

2020-03-10 22:18 UTC, a-ivanov requested changes

2020-03-10 22:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
http://bit.ly/3aD3KAp нарушение SRP

2020-03-10 22:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +            if (room.getName().equals("hall")) {
нарушение SRP http://bit.ly/2VO81g0

2020-03-10 22:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                SensorCommand command = new SensorCommand(CommandType.LIGHT_OFF, light.getId());
Передайте отправщика команд как зависимостмь в констуркторе http://bit.ly/2TBH1Pg

2020-03-10 22:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeJsonReader.java
> +    SmartHome readSmartHome(String path) throws IOException {
leaky abstraction http://bit.ly/2v2kMZw

2020-03-12 14:12 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
исправил во 2ой домашке

2020-03-12 14:13 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +            if (room.getName().equals("hall")) {
исправил во 2ой домашке

2020-03-12 14:13 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                SensorCommand command = new SensorCommand(CommandType.LIGHT_OFF, light.getId());
исправил во 2ой домашке

2020-03-12 14:13 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/SmartHomeJsonReader.java
> +    SmartHome readSmartHome(String path) throws IOException {
исправил во 2ой домашке

2020-03-12 17:07 UTC, a-ivanov requested changes
Удалите бинарные ненужные файлы из репозитория http://bit.ly/38EfxwM и перенесите все исправления по 1дз в эту ветку. 2дз - это 2дз.

2020-03-17 16:06 UTC, a-ivanov approved these changes

2020-03-24 13:12 UTC, merged