Homework 2 Ildar Zinatulin
ildarzinatulin/smart-home-2020 pull request #2
Opened 2020-03-11 21:04 UTC by ildarzinatulin

2020-03-15 21:46 UTC, a-ivanov requested changes
И удалите бинарные файлы из репозитория.

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
IOException тут разве нужно?

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +    private void ternOffAllLight() {
**turn**OffAllLight

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/RandomEventHandler.java
> +public class RandomEventHandler {
Плохое название - привязка к созданию событий, хотя тут класс другое делает, переименуйте. И он не EventHandler, для этого етсь отдельный интерфейс, не надо путать.

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/RandomSensorEventCreator.java
> +    SensorEvent getNextSensorEvent() {
Можно сделать интерфейс SensorEventCreator и его имплементацию RandomSensorEventCreator, везде как засисмость использовать интерфейс SensorEventCreator.

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    Collection<Door> getDoors() {
Удалите этот метод, он не используется и больше не нужен по 2му дз.

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    Collection<Light> getLights() {
Удалите этот метод, он не используется и больше не нужен по 2му дз.

2020-03-15 21:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        rooms.forEach(room -> room.execute(action));
Забыли дом http://bit.ly/2IOqtgT

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +    private void ternOffAllLight() {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/RandomEventHandler.java
> +public class RandomEventHandler {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/RandomSensorEventCreator.java
> +    SensorEvent getNextSensorEvent() {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    Collection<Door> getDoors() {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    Collection<Light> getLights() {
исправил

2020-03-17 12:57 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        rooms.forEach(room -> room.execute(action));
исправил

2020-03-17 13:50 UTC, closed without merging

2020-03-17 16:15 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    Collection<Room> getRooms() {
Этот метод тоже можно удалить

2020-03-17 16:21 UTC, a-ivanov commented
Зачёт.