Homework 3 Ильдар Зинатулин
ildarzinatulin/smart-home-2020 pull request #4
Opened 2020-03-20 16:49 UTC by ildarzinatulin

2020-03-23 14:33 UTC, a-ivanov requested changes

2020-03-23 14:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartAlarmDevice.java
> +public class SmartAlarmDevice implements AlarmDevice{
См. шаблон состояние https://refactoring.guru/ru/design-patterns/state Клиенты сигнализации не должны знать, что она использует состояния. Это имплементация. Это не значит, что надо убирать интерфейс AlarmDevice с самих состояний, но его надо убрать с сигнализации. Ею пользуются только для проверки, включена она или нет. Ну для отключения / включения тоже.

2020-03-23 14:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    Collection<Room> getRooms() {
Этот метод вообще с 2 дз надо было убрать, никто не должен знать, из чего состоит дом.

2020-03-23 14:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmDeviceDecorator.java
> +public class AlarmDeviceDecorator implements EventHandler {
А этот класс вообще гдето используется?

2020-03-23 14:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        loopOfHandlesSensorEvents.run();
Помните, что тут надо декорировать обработку событий таким образом, чтобы отправлялось всего 1 смс, если приходит событие и сигнализация активирована https://bit.ly/2UoOLDs

2020-03-23 14:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CommandSender.java
> +    void sendCommand(SensorCommand command) {
Можно выделить в интерфейс.

2020-03-24 13:55 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/SmartAlarmDevice.java
> +public class SmartAlarmDevice implements AlarmDevice{
Мы просто также делали на лекции. Исправил.

2020-03-24 13:55 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    Collection<Room> getRooms() {
Исправил

2020-03-24 13:55 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/AlarmDeviceDecorator.java
> +public class AlarmDeviceDecorator implements EventHandler {
Исправил

2020-03-24 13:55 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        loopOfHandlesSensorEvents.run();
исправил

2020-03-24 13:55 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/CommandSender.java
> +    void sendCommand(SensorCommand command) {
исправил

2020-03-26 13:10 UTC, a-ivanov requested changes
Поправьте с ALARM_DEACTIVATE и зачет.

2020-03-26 13:10 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmDeviceDecorator.java
> +        if (alarmDevice.isActivated()) {
Декоратор выполняет свою работу правильно. Единственное, что никто не сможет обработать событие ALARM_DEACTIVATE после активации сигнализации. Либо уберите событие ALARM_DEACTIVATE, либо добавьте возможность отключать сигнализацию.

2020-04-01 10:36 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/AlarmDeviceDecorator.java
> +        if (alarmDevice.isActivated()) {
исправлено

2020-04-03 11:56 UTC, a-ivanov approved these changes

2020-04-03 11:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmDeviceDecorator.java
> +        if (alarmDevice.isActivated() && event.getType() != ALARM_DEACTIVATE) {
Ну так себе правка, может появиться больше новых необрабатываемых типов событий

2022-04-06 09:49 UTC, merged