Homework 4 Ildar Zinatulin
ildarzinatulin/smart-home-2020 pull request #5
Opened 2020-03-24 19:56 UTC by ildarzinatulin

2020-03-30 15:37 UTC, a-ivanov requested changes

2020-03-30 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        List<EventHandler> handlers = Arrays.asList(new DoorEventHandler(smartHome), new LightEventHandler(smartHome),
Обработчики - отдельными бинами https://bit.ly/2UrPgOg

2020-03-30 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandlerAdapter.java
> +    private final Map<String, SensorEventType> convertType = Map.of(
Не надо прибивать гвоздями мапу. Сделайте ее аргументом в конструкторе. Ее можно конфигурировать тоже отдельным бином.

2020-04-01 11:18 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        List<EventHandler> handlers = Arrays.asList(new DoorEventHandler(smartHome), new LightEventHandler(smartHome),
исправил

2020-04-01 11:18 UTC, ildarzinatulin commented on src/main/java/ru/sbt/mipt/oop/EventHandlerAdapter.java
> +    private final Map<String, SensorEventType> convertType = Map.of(
исправил

2020-04-03 13:06 UTC, a-ivanov approved these changes

2020-04-03 13:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandlerAdapter.java
> +    private final Map<String, SensorEventType> convertType = Map.of(
Лучше удалять неиспользуемый код.

2022-04-06 09:49 UTC, merged